name: 'On Called for Building Matrix'

on:
  workflow_call:
    inputs:
      matrix_path:
        type: string
        required: false
        description: File path that contains the matrix JSON array.
        default: './custom-connectors-in-a-day/infra/gha-matrix.json'
    outputs:
      matrix_json:
        description: function app names in the format of JSON string array
        value: ${{ jobs.build_matrix.outputs.matrix_json }}

jobs:
  build_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix_json: ${{ steps.build_json.outputs.matrix_json }}

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Build JSON array for matrix
      id: build_json
      shell: pwsh
      run: |
        $json = Get-Content -Path ${{ inputs.matrix_path }} -Raw | `
            ConvertFrom-Json -NoEnumerate | `
            ConvertTo-Json -Compress
        
        echo "matrix_json=$json" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
