openapi: 3.0.1
info:
  title: BFF
  description: This is the BFF API to API Key Auth and Basic Auth.
  version: '1.0'
servers:
  - url: https://apim-{{AZURE_ENV_NAME}}.azure-api.net/bff
paths:
  /greeting:
    get:
      tags:
        - greeting
      summary: Greeting
      operationId: Greeting
      parameters:
        - name: name
          in: query
          description: The **Name** parameter
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/greetingResponse'
              example:
                message: string
      security:
        - apiKeyHeader: [ ]
        - apiKeyQuery: [ ]
  /profile:
    get:
      tags:
        - profile
      summary: Profile
      operationId: Profile
      responses:
        '200':
          description: The OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/atlassianUser'
              example:
                type: string
                accountId: string
                accountType: string
                email: string
                publicName: string
                profilePicture:
                  path: string
                  width: 0
                  height: 0
                  isDefault: true
                displayName: string
                isExternalCollaborator: true
                _expandable:
                  operations: string
                  personalSpace: string
                _links:
                  self: string
                  _base: string
                  context: string
      security:
        - apiKeyHeader: [ ]
        - apiKeyQuery: [ ]
        - basicAuth: [ ]
components:
  schemas:
    greetingResponse:
      type: object
      properties:
        message:
          type: string
    atlassianUser:
      type: object
      properties:
        type:
          type: string
        accountId:
          type: string
        accountType:
          type: string
        email:
          type: string
        publicName:
          type: string
        profilePicture:
          $ref: '#/components/schemas/profilepicture'
        displayName:
          type: string
        isExternalCollaborator:
          type: boolean
        _expandable:
          $ref: '#/components/schemas/expandable'
        _links:
          $ref: '#/components/schemas/links'
    expandable:
      type: object
      properties:
        operations:
          type: string
        personalSpace:
          type: string
    links:
      type: object
      properties:
        self:
          type: string
        _base:
          type: string
        context:
          type: string
    profilepicture:
      type: object
      properties:
        path:
          type: string
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        isDefault:
          type: boolean
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
    basicAuth:
      type: http
      scheme: basic
