name: 'On Called for Setting GitHub Secrets'

on:
  workflow_call:
    inputs:
      azure_env_name:
        type: string
        required: true
        description: 'Azure environment (resource) name'
      azure_location:
        type: string
        required: false
        description: 'Azure resource location. Default to `koreacentral`'
        default: 'koreacentral'
      azure_subscription_id:
        type: string
        required: true
        description: 'Azure subscription ID'
      # azure_principal_id:
      #   type: string
      #   required: true
      #   description: 'Azure service principal ID'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set GitHub secrets
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        gh secret set AZURE_ENV_NAME --body ${{ inputs.azure_env_name }} --repo ${{ github.repository }}
        gh secret set AZURE_LOCATION --body ${{ inputs.azure_location }} --repo ${{ github.repository }}
        gh secret set AZURE_SUBSCRIPTION_ID --body ${{ inputs.azure_subscription_id }} --repo ${{ github.repository }}
        # gh secret set AZURE_PRINCIPAL_ID --body ${{ inputs.azure_principal_id }} --repo ${{ github.repository }}
