name: 'On Called for Doing Build & Test & Upload'

on:
  workflow_call:
    inputs:
      matrix_json:
        type: string
        required: true
        description: Matrix JSON array
      artifact_name:
        type: string
        required: false
        description: Artifact name
        default: 'app'
      is_pullrequest:
        type: string
        required: false
        description: Value indicating whether the caller event is pull request or not
        default: 'false'

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(inputs.matrix_json) }}

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore ./custom-connectors-in-a-day

    - name: Build solution
      shell: bash
      run: |
        dotnet build ./custom-connectors-in-a-day -c Release -f net6.0

    - name: Test solution
      shell: bash
      run: |
        dotnet test ./custom-connectors-in-a-day -c Release -f net6.0

    - name: Create artifacts
      if: inputs.is_pullrequest == 'false'
      shell: bash
      run: |
        dotnet publish ./custom-connectors-in-a-day -c Release -f net6.0

    - name: Add app paths to env
      if: inputs.is_pullrequest == 'false'
      shell: pwsh
      run: |
        $appPath = "custom-connectors-in-a-day/src/${{ matrix.app.path }}/bin/Release/net6.0/publish"

        echo "APP_PATH=$appPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Upload app artifact
      if: inputs.is_pullrequest == 'false'
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.artifact_name }}-${{ matrix.app.name }}"
        path: "${{ github.workspace }}/${{ env.APP_PATH }}"
        retention-days: 3
